### ISSUE TITLE
Le bouton de l'info touristique et de la loupe se remplacent une fois activés par un point violet

### ISSUE THREAD

**Issue by cmozzati** [tzi/zupple-feedbacks#10]
J'ai pas de screenshots mais c'est comme si le picto, une fois cliqué, se remplacait par une autre image (celui du gros point violet)

**Comment by cmozzati** [comment]
Ça y est j'ai reproduit : ![IMG_2839](https://user-images.githubusercontent.com/3350525/61182499-62f14500-a634-11e9-8c1f-c4c07ea301d7.PNG)

**Comment by annabelle8** [comment]
Alors ça c'est bizarre !! C'est systématique chez toi ? Pour le moment je n'arrive pas à reproduire.

**Comment by tzi** [comment]
Petit commentaire, le screenshot provient d'un iPhone

**Comment by cmozzati** [comment]
Non c'est pas systématique, j'ai pas encore compris quand ça arrivait

**Comment by annabelle8** [comment]
On a pas réussi à reproduire mais on pense avoir compris d'où ça vient ! On a livré un correctif, si tu retombes dessus dis-le nous c'est qu'on s'est ratés... Merci !
