### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by annabelle8** [tzi/zupple-feedbacks#102]
- [x] Detect story badge
 - [x] Detect XP badge
 - [x] Detect season badge
 - [ ] Add beta badge / beta status
 - [x] Display badge
 - [x] Display future badges
 - [x] API to reclcul badges

**Comment by tzi** [comment]
Inspiration : https://codepen.io/tzi/pen/pMdKmE?editors=0100

![Capture d’écran de 2019-08-05 12-24-35](https://user-images.githubusercontent.com/415891/62457897-02a97b00-b77c-11e9-95ec-8c1438ea4773.png)
