### ISSUE TITLE
Augmenter la zone de clic sur le point bleu des énigmes déjà faites

### ISSUE THREAD

**Issue by cmozzati** [tzi/zupple-feedbacks#11]
Il faut vraiment se concentrer pour bien cliquer afin de revoir une énigme 😅

**Comment by cmozzati** [comment]
D'ailleurs je pense qu'il faut faire ça sur tous les petits points (violets aussià

**Comment by tzi** [comment]
:+1: Bien vu !

Envoyé depuis ProtonMail mobile

-------- Message d'origine --------

**Comment by tzi** [comment]
Done!
