### ISSUE TITLE
Quand on zoome sur la map, ça dézoome tout seul pour revenir à l'état par défaut

### ISSUE THREAD

**Issue by cmozzati** [tzi/zupple-feedbacks#12]
Ça le fait au pinch et au double-clic sur la map pour zoomer

**Comment by tzi** [comment]
Intéressant. Ca se produit sous iOS et sous Android ?

Envoyé depuis ProtonMail mobile

-------- Message d'origine --------

**Comment by cmozzati** [comment]
Uniquement sur iOS

**Comment by cmozzati** [comment]
Ah non en fait ça le fait aussi sur Android mais uniquement quand on se déplace :
- on zoome, ça reste 
- on se déplace dans la zone zoomée, ça dézoome

Alors que sur iOS ça dézoome au bout de qq secondes même sans action utilisateur
