### ISSUE TITLE
La croix du bandeau du parcours flotte un peu 

### ISSUE THREAD

**Issue by cmozzati** [tzi/zupple-feedbacks#15]
Caler en haut sur le texte et à droite sur le €
![IMG_2817](https://user-images.githubusercontent.com/3350525/61182341-c62da800-a631-11e9-988e-9d4173f2cc67.PNG)

**Comment by annabelle8** [comment]
Corrigé sur android mais toujours présent sur iOs

**Comment by tzi** [comment]
C'est corrigé !!
![bs_realios_Mobile_iPhone XS-12 0](https://user-images.githubusercontent.com/415891/61579577-2e372f00-ab07-11e9-9175-0713d60caebb.jpg)
