### ISSUE TITLE
Pour revenir à l'énigme après avoir rentré une mauvaise réponse, il n'y a pas de bouton dans l'UI

### ISSUE THREAD

**Issue by cmozzati** [tzi/zupple-feedbacks#19]
Sur iOS, c'est intuitif de cliquer ailleurs pour revenir sur l'interface, mais sur Android, Angélique a eu à chaque fois le réflexe de cliquer sur le bouton "retour" du téléphone et du coup est revenue en arrière en perdant Zupple. 
J'ajouterais un bouton "Revenir à l'énigme" ou quelque chose du genre

**Comment by tzi** [comment]
Done!

- On a rajouter la gestion du bouton "retour" du téléphone... à voir si ça crée pas de nouveaux bugs parce que le code est un peu tordu :)
- On a rajouté une croix sur l'interface de réponse

![Capture d’écran de 2019-07-18 10-29-34](https://user-images.githubusercontent.com/415891/61442044-22047380-a947-11e9-981f-62c523212e4f.png)
