### ISSUE TITLE
Le point GPS du joueur actif manque de contraste (my bad)

### ISSUE THREAD

**Issue by cmozzati** [tzi/zupple-feedbacks#23]
Peut-être le changer de couleur ou changer la couleur de l'animation du contour ?

**Comment by annabelle8** [comment]
Ca marche, on va pousser une version avec cette couleur : #BD10E0
Je pense qu'elle contraste mieux. Et l'idée dans pas longtemps est de faire que si on spot est à ta portée il ait le même halo que ta position. Du coup les spots violets avec cette couleur de halo ça peut bien marcher aussi je pense.
