### ISSUE TITLE
Quand on actualise la page d'une énigme à distance, erreur 'rapprochez-vous de l'énigme'

### ISSUE THREAD

**Issue by syb69** [tzi/zupple-feedbacks#24]
Lorsque je reprends une énigme à distance, une fois sur l'énigme, je tire la page vers le bas, ce qui actualise la page, et j'arrive sur l'erreur "Rapprochez-vous du lieu de l'énigme pour jouer" puis retour sur la carte (d'où je peux retourner sur l'énigme et y répondre tant que je n'actualise pas)
[
![rapprochez_vous_enigme](https://user-images.githubusercontent.com/43068597/61184680-ffc1db80-a650-11e9-8974-0b64aaa294ba.png)
](url)

**Comment by tzi** [comment]
C'est voulu, mais c'est pas génial :disappointed: 

Idée pour Anna et moi : 
 - Faire un portail pour la géoloc, donc qui arriverait avant le calcul des droits de lecture de l'énigme
 - Faire un fetch de l'énigme avec une option si on n'a pas de géoloc active pour ne pas démarrer la partie si elle n'est pas trouvée

**Comment by tzi** [comment]
C'est fait !
Par contre ça ouvre la popup de l'histoire à chaque fois... du coup je ne ferme pas encore ce ticket :panda_face:

**Comment by tzi** [comment]
Cette fois-ci on peut clore cette issue :tada:
