### ISSUE TITLE
Plus mettre en valeur l'avancement d'un parcours dans le menu parcours ou sur la carte dans le bandeau en haut.

### ISSUE THREAD

**Issue by syb69** [tzi/zupple-feedbacks#30]
Lorsqu'on a fini un parcours, 
- dans le menu des parcours la barre d'avancement est pleine,
- dans le bandeau sur la carte du parcours, pas d'info d'avancement (sauf les couleurs des points) 

Jjaurai trouvé pas mal de voir 3 / 5 pour 3 énigmes faites sur 5, ou un 5 / 5 quand tout est fait. 

Et même un "tampon" terminé sur le bloc du parcours.

**Comment by annabelle8** [comment]
Normalement dans le bandeau du parcours sur la carte tu as bien la barre d'avancement aussi. Tu l'as ? 

![image](https://user-images.githubusercontent.com/6190842/61189141-6b279f80-a689-11e9-8d62-cfbce1960e4d.png)

**Comment by syb69** [comment]
Oui je l'ai bien aussi ! Mais en fait comme la barre est pleine, je n'ai plus fait attention que c'était la barre d'avancement aussi et pas juste de la déco😋
