### ISSUE TITLE
Fiabiliser la boussole

### ISSUE THREAD

**Issue by annabelle8** [tzi/zupple-feedbacks#43]
Boussole

**Comment by tzi** [comment]
Manque de repère pour réussir à se déplacer dans la ville.
Proposition de Christelle : Mettre en évidence le champs de vision grâce à la boussole (mais c'est pas super stable)

**Comment by tzi** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/DeviceOrientationEvent
