### ISSUE TITLE
Popup parcours : croix et bouton de validation ont le même effet

### ISSUE THREAD

**Issue by joseph-colin** [tzi/zupple-feedbacks#5]
Dans le menu parcours, quand on sélectionne un parcours, la popup apparaît :
- la croix en haut a droite et le bouton de validation envoient tous les deux sur la carte
- je m'attendrais à ce que la croix ferme plutôt la popup et rester sur la liste des parcours pour en choisir un autre.

**Comment by annabelle8** [comment]
![logo](https://user-images.githubusercontent.com/6190842/61171777-8eb0f400-a57c-11e9-8778-a39d9723f5e9.png)

**Comment by annabelle8** [comment]
doublon #1

**Comment by tzi** [comment]
on note !
