### ISSUE TITLE
Quand on clique sur voir les énigmes de Cassandre on ne voit pas tout

### ISSUE THREAD

**Issue by syb69** [tzi/zupple-feedbacks#58]
Quand on clique sur voir les énigmes de Cassandre on ne voit pas tout.
Je m'attendais à avoir un zoom qui me permettrait de voir les 5 énigmes.
![Screenshot_20190721-091957](https://user-images.githubusercontent.com/43068597/61588308-a2baae00-ab99-11e9-84c8-1f62c9bf1901.png)

**Comment by syb69** [comment]
En fait, on reste sur le dernier niveau de zoom qu'on avait donc. Je trouve que ça serait bien de montrer tous les points du parcours.

**Comment by syb69** [comment]
Et du coup c'esr pareil sur les autres parcours !

**Comment by annabelle8** [comment]
Ah oui carrément ! Merci on va faire ça !

**Comment by tzi** [comment]
Bien vu Syb !! C'est corrigé :)
