### ISSUE TITLE
Barre d'avancement trop proche de "Énigme 1" pour cassandre

### ISSUE THREAD

**Issue by syb69** [tzi/zupple-feedbacks#62]
Sur la carte, dans un parcours, la barre d'avancement est trop proche de "Énigme 1" pour cassandre. Voir la diff avec cash.
![Screenshot_20190721-105531](https://user-images.githubusercontent.com/43068597/61589168-9db02b80-aba6-11e9-8614-a98c567fd218.png)
![Uploading Screenshot_20190721-105421.png…]()

**Comment by tzi** [comment]
Done!
