### ISSUE TITLE
Animation cash

### ISSUE THREAD

**Issue by annabelle8** [tzi/zupple-feedbacks#64]
Croix étriquée sur iphone ( plus haute que large)

**Comment by tzi** [comment]
![IMG-20190721-WA0008](https://user-images.githubusercontent.com/415891/61597680-b3a80580-ac13-11e9-9c76-b8c00ca98f65.jpg)

**Comment by tzi** [comment]
Done!

![bs_realios_Mobile_iPhone X-11 0](https://user-images.githubusercontent.com/415891/61597854-9ffd9e80-ac15-11e9-821f-c1a1135e18ae.jpg)
