### ISSUE TITLE
Ameliorer style sms - retours syb

### ISSUE THREAD

**Issue by annabelle8** [tzi/zupple-feedbacks#65]

**Comment by tzi** [comment]
![IMG-20190721-WA0009](https://user-images.githubusercontent.com/415891/61597686-c6bad580-ac13-11e9-92fb-697311a23f74.jpg)

**Comment by tzi** [comment]
Proposition de correction : 

![Capture d’écran - 2019-07-22 à 00 39 10](https://user-images.githubusercontent.com/415891/61598123-354e6200-ac19-11e9-8ab1-302fecdbc1c8.png)
